web/router.ex
defmodule Takso.Router do
  use Takso.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    # plug Takso.Authentication, repo: Takso.Repo
  end

  pipeline :browser_auth do  
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end
  
  pipeline :require_login do
    plug Guardian.Plug.EnsureAuthenticated, handler: Takso.SessionController    
    plug :guardian_current_user
  end

  def guardian_current_user(conn, _) do
    Plug.Conn.assign(conn, :current_user, Guardian.Plug.current_resource(conn))
  end

  scope "/", Takso do
    pipe_through :browser # Use the default browser stack
    resources "/sessions", SessionController, only: [:new, :create]
  end

  scope "/", Takso do
    pipe_through [:browser, :browser_auth]
    get "/", PageController, :index
    resources "/users", UserController
  end

  scope "/", Takso do
    pipe_through [:browser, :browser_auth, :require_login]

    get "/bookings/summary", BookingController, :summary
    resources "/bookings", BookingController
    resources "/sessions", SessionController, only: [:delete]
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end

  pipeline :auth_api do
    plug Guardian.Plug.EnsureAuthenticated, handler: Takso.SessionAPIController    
    plug :guardian_current_user
  end

  scope "/api", Takso do
    pipe_through :api
    post "/sessions", SessionAPIController, :create
  end

  scope "/api", Takso do
    post "/sign-up", UserAPIController, :create
    pipe_through [:api, :auth_api]
    delete "/sessions/:id", SessionAPIController, :delete
    post "/bookings", BookingAPIController, :create
    patch "/bookings/:id", BookingAPIController, :update
    get "/bookings/summary", BookingAPIController, :summary
    patch "/pay/:id", BookingAPIController, :pay
    post "/book-place", BookingAPIController, :create2
    get "/user/", UserAPIController, :get
    put "/user/", UserAPIController, :update
  end
end

web/views/booking_view.ex
defmodule Takso.BookingView do
  use Takso.Web, :view
end

web/templates/booking/index.html.eex
<h2>Listing bookings</h2>

<table class="table">
  <thead>
    <tr>
      <th>Pickup address</th>
      <th>Drop off address</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
<%= for booking <- @bookings do %>
    <tr>
      <td><%= booking.pickup_address %></td>
      <td><%= booking.dropoff_address %></td>
      <td><%= booking.status %></td>
     <td class="text-right">
        <span><%= link "Show", to: booking_path(@conn, :show, booking), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: booking_path(@conn, :edit, booking), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: booking_path(@conn, :delete, booking), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/booking/new.html.eex
<%= form_for @changeset, booking_path(@conn, :create), fn booking -> %>
  <div class="form-group">
    <%= label booking, :pickup_address, class: "control-label" %>
    <%= text_input booking, :pickup_address, id: "pickup_address", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label booking, :dropoff_address, class: "control-label" %>
    <%= text_input booking, :dropoff_address, id: "dropoff_address", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= submit "Submit", id: "submit_button", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/booking/summary.html.eex
<h2>Listing accepted bookings</h2>

<table class="table">
  <thead>
    <tr>
      <th>Taxi identifier</th>
      <th>Number of accepted bookings</th>
    </tr>
  </thead>
  <tbody>
<%= for t <- @tuples do %>
    <tr>
      <td><%= elem(t, 0) %></td>
      <td><%= elem(t, 1) %></td>
    </tr>
<% end %>
  </tbody>
</table>